Driver/executor event timestamps
spotinst/wave-operator pull request #12
Opened 2020-12-15 12:23 UTC by thorsteinnth

- Save driver and executor pod creation and deletion timestamps
- Save pod labels
- Fetch `addTime` for executors from Spark API

2020-12-15 17:59 UTC, ntfrnzn requested changes
I liked the version setup as it was, but we can talk about it

2020-12-15 17:59 UTC, ntfrnzn commented on Dockerfile
> +COPY VERSION_NUMBER VERSION_NUMBER
VERSION_NUMBER contains the raw string, VERSION contains the git hash
Makefile calls target "version" as part of the "docker-build" target
https://github.com/spotinst/wave-operator/blob/main/Makefile.devel#L77 to write the VERSION file

2020-12-16 08:38 UTC, thorsteinnth commented on Dockerfile
> +COPY VERSION_NUMBER VERSION_NUMBER
my mistake, reverted.

2020-12-16 16:00 UTC, ntfrnzn approved these changes

2020-12-16 16:09 UTC, merged