[src] BGD-853 - add `wave-application-id` label to the wave spark app CR
spotinst/wave-operator pull request #65
Opened 2021-06-16 11:49 UTC by alextarasov-spot

2021-06-16 13:55 UTC, arnarpall commented on controllers/sparkpod_controller.go
> +		waveApplicationId = waveApplicationIdLabel
I would suggest just returning `waveApplicationIdLabel` here
and then just return an empty string at the bottom of the method.

This makes for good readability since you don't have to follow the `waveApplicationId` variable.

2021-06-16 13:55 UTC, arnarpall requested changes
Just a small comment that I believe we should fix

2021-06-17 12:13 UTC, thorsteinnth commented on internal/config/config.go
> +	WaveConfigLabelWaveApplicationId      = "wave.spot.io/wave-application-id"
I think we should put this constant in the spark pod controller. The config package deals with user supplied configuration.

2021-06-23 09:28 UTC, arnarpall approved these changes

2021-06-23 09:30 UTC, arnarpall commented on internal/config/config.go
> +	WaveConfigLabelWaveApplicationId      = "wave.spot.io/wave-application-id"
I agree

2021-06-23 13:22 UTC, merged